apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: bots
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: code-server-storage
  resources:
    requests:
      storage: 2Gi