apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-${BOT_ID}
  namespace: bots
  labels:
    app: code-server
    bot-id: ${BOT_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
      bot-id: ${BOT_ID}
  template:
    metadata:
      labels:
        app: code-server
        bot-id: ${BOT_ID}
    spec:
      serviceAccountName: code-server
      securityContext:
        fsGroup: 1000
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: code-server
        image: codercom/code-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: ${PASSWORD}
        - name: SHELL
          value: "/bin/bash"
        - name: HOME
          value: "/home/coder"
        - name: BOT_ID
          value: ${BOT_ID}
        - name: REPO_URL
          value: ${REPO_URL}
        volumeMounts:
        - name: code-server-data
          mountPath: /home/coder/project
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "
                mkdir -p /home/coder/project && \
                cd /home/coder/project && \
                if [ ! -d .git ]; then \
                  git clone ${REPO_URL} . || echo 'Repository already exists'; \
                fi && \
                code-server --install-extension ms-python.python || true && \
                code-server --install-extension dbaeumer.vscode-eslint || true && \
                code-server --install-extension esbenp.prettier-vscode || true
              "]
      volumes:
      - name: code-server-data
        persistentVolumeClaim:
          claimName: code-${BOT_ID}-pvc