apiVersion: v1
kind: Service
metadata:
  name: code-${BOT_ID}
  namespace: bots
  labels:
    app: code-server
    bot-id: ${BOT_ID}
spec:
  selector:
    app: code-server
    bot-id: ${BOT_ID}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP