apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: bots
  labels:
    app: code-server
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: code-server-storage-local
  resources:
    requests:
      storage: 1Gi