apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-${BOT_ID}-pvc
  namespace: bots
  labels:
    app: code-server
    bot-id: ${BOT_ID}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: code-server-storage
  resources:
    requests:
      storage: 1Gi