apiVersion: v1
kind: Secret
metadata:
  name: code-server-tls
  namespace: bots
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CRT}  # Replace with your base64 encoded certificate
  tls.key: ${TLS_KEY}  # Replace with your base64 encoded private key