apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: code-server-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-pv
  namespace: bots
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: code-server-storage
  hostPath:
    path: /data/code-server
    type: DirectoryOrCreate