apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-functions
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-functions-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes", "pods", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-functions-binding
subjects:
- kind: ServiceAccount
  name: edge-functions
  namespace: default
roleRef:
  kind: ClusterRole
  name: edge-functions-role
  apiGroup: rbac.authorization.k8s.io
